#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := cross.cpp cursor.cpp circle.cpp tictactoegrid.cpp tictactoegridspot.cpp

# header files in this project
HEADERS := tictactoedrawable.hpp cross.hpp cursor.hpp circle.hpp tictactoegrid.hpp tictactoegridspot.hpp game.hpp bigdrawer.hpp coutdrawer.hpp

# other places to look for files for this project
SEARCH  := 

# set REATIVE to the next higher directory 
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../../v2cpse2-examples/
include $(RELATIVE)Makefile.native
